[package]
name = "rusty-kern"
version = "0.1.0"
edition = "2018"

[workspace]
members = [
    "imager",
]

[dependencies]
bootloader = "0.10.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
