[package]
name = "rusty-kern"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlibc = "1.0.0"
uefi = "0.12.0"
uefi-services = "0.9.0"

[features]
qemu = ["uefi-services/qemu"]
