[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-rusty-kern.json"

[target.'cfg(target_os = "none")']
runner = "cargo run --package imager --target=x86_64-unknown-linux-gnu --"

[alias]
image = "run --release -- --no-run"
